public let movieLibrary: [Movie] = [
    Movie(title: "(500) Days of Summer", portugueseTitle: "(500) Dias com Ela", genre: .comedy, duration: 5700, year: 2009),
    Movie(title: "27 Dresses", portugueseTitle: "Vestida para Casar", genre: .comedy, duration: 6660, year: 2008),
    Movie(title: "A Dangerous Method", portugueseTitle: "Um Método Perigoso", genre: .biography, duration: 5940, year: 2011),
    Movie(title: "A Serious Man", portugueseTitle: "Um Homem Sério", genre: .comedy, duration: 6360, year: 2009),
    Movie(title: "Across the Universe", genre: .drama, duration: 7980, year: 2007, isFavorite: true),
    Movie(title: "Beginners, así se siente el amor", portugueseTitle: "Toda Forma de Amor", genre: .comedy, duration: 6300, year: 2010),
    Movie(title: "Dear John", portugueseTitle: "Querido John", genre: .drama, duration: 6480, year: 2010),
    Movie(title: "Enchanted", portugueseTitle: "Encantada", genre: .animation, duration: 6420, year: 2007),
    Movie(title: "Fireproof", portugueseTitle: "À Prova de Fogo", genre: .drama, year: 2008),
    Movie(title: "Four Christmases", portugueseTitle: "Surpresas do Amor", genre: .comedy, duration: 5280, year: 2008),
    Movie(title: "Ghosts of Girlfriends Past", portugueseTitle: "Minhas Adoráveis Ex-Namoradas", genre: .comedy, year: 2009),
    Movie(title: "Gnomeo and Juliet", genre: .animation, year: 2011),
    Movie(title: "Going the Distance", portugueseTitle: "Amor à Distância", genre: .comedy, year: 2010),
    Movie(title: "Good Luck Chuck", portugueseTitle: "Maldita Sorte", genre: .comedy, duration: 6060, year: 2007),
    Movie(title: "He's Just Not That Into You", portugueseTitle: "Ele Não Está Tão a Fim de Você", genre: .comedy, duration: 7740, year: 2009),
    Movie(title: "High School Musical 3: Senior Year", portugueseTitle: "High School Musical 3: Ano da Formatura", genre: .comedy, duration: 6720, year: 2008),
    Movie(title: "I Love You Phillip Morris", portugueseTitle: "O Golpista do Ano", genre: .biography, duration: 6120, year: 2009),
    Movie(title: "It's Complicated", portugueseTitle: "Simplesmente Complicado", genre: .comedy, year: 2009),
    Movie(title: "Jane Eyre", genre: .drama, duration: 7200, year: 2011),
    Movie(title: "Just Wright - In diesem Spiel zählt jeder Treffer", portugueseTitle: "Jogada Certa", genre: .comedy, year: 2010),
    Movie(title: "Killers", portugueseTitle: "Par Perfeito", genre: .action, duration: 6000, year: 2010),
    Movie(title: "Knocked Up", portugueseTitle: "Ligeiramente Grávidos", genre: .comedy, duration: 7740, year: 2007),
    Movie(title: "Leap Year", portugueseTitle: "Casa Comigo?", genre: .comedy, year: 2010),
    Movie(title: "Letters to Juliet", portugueseTitle: "Cartas para Julieta", genre: .adventure, year: 2010),
    Movie(title: "License to Wed", portugueseTitle: "Licença para Casar", genre: .comedy, duration: 5460, year: 2007),
    Movie(title: "Life as We Know It", portugueseTitle: "Juntos Pelo Acaso", genre: .comedy, year: 2010),
    Movie(title: "Love & Other Drugs", portugueseTitle: "Amor e Outras Drogas", genre: .comedy, duration: 6720, year: 2010),
    Movie(title: "Love Happens", portugueseTitle: "O Amor Acontece", genre: .drama, year: 2009),
    Movie(title: "Made of Honor", portugueseTitle: "O Melhor Amigo da Noiva", genre: .comedy, duration: 6060, year: 2008),
    Movie(title: "Mamma Mia!", portugueseTitle: "Mamma Mia! O Filme", genre: .comedy, duration: 6480, year: 2008),
    Movie(title: "Marley and Me", portugueseTitle: "Marley & Eu", genre: .comedy, year: 2008),
    Movie(title: "Midnight in Paris", portugueseTitle: "Meia-Noite em Paris", genre: .comedy, year: 2011),
    Movie(title: "Miss Pettigrew Lives for a Day", portugueseTitle: "A Vida num Só Dia", genre: .comedy, duration: 5520, year: 2008),
    Movie(title: "Monte Carlo", genre: .adventure, year: 2011),
    Movie(title: "Music and Lyrics", portugueseTitle: "Letra e Música", genre: .comedy, duration: 5700, year: 2007),
    Movie(title: "My Week with Marilyn", portugueseTitle: "Sete Dias com Marilyn", genre: .biography, duration: 5940, year: 2011),
    Movie(title: "New Year's Eve", portugueseTitle: "Noite de Ano Novo", genre: .comedy, duration: 6780, year: 2011),
    Movie(title: "Nick and Norah's Infinite Playlist", portugueseTitle: "Nick & Norah: Uma Noite de Amor e Música", genre: .comedy, duration: 5400, year: 2008),
    Movie(title: "No Reservations", portugueseTitle: "Sem Reservas", genre: .comedy, duration: 6240, year: 2007),
    Movie(title: "Not Easily Broken", portugueseTitle: "Ponto de Decisão", genre: .drama, duration: 5940, year: 2009),
    Movie(title: "One Day (Siempre el mismo día)", portugueseTitle: "Um Dia", genre: .drama, duration: 6420, year: 2011),
    Movie(title: "Our Family Wedding", portugueseTitle: "Nossa União, Muita Confusão", genre: .comedy, year: 2010),
    Movie(title: "Over Her Dead Body", portugueseTitle: "Nem por Cima do Meu Cadáver", genre: .comedy, duration: 5700, year: 2008),
    Movie(title: "P.S. I Love You", portugueseTitle: "P.S. Eu te Amo", genre: .drama, duration: 7560, year: 2007),
    Movie(title: "Penelope", genre: .comedy, duration: 6240, year: 2006),
    Movie(title: "Rachel Getting Married", portugueseTitle: "O Casamento de Rachel", genre: .drama, duration: 6780, year: 2008),
    Movie(title: "Remember Me", portugueseTitle: "Viva - A Vida é uma Festa", genre: .animation, year: 2017),
    Movie(title: "Sex and the City", genre: .comedy, duration: 1800, year: 1998),
    Movie(title: "Sex and the City 2", genre: .comedy, duration: 8760, year: 2010),
    Movie(title: "She's Out of My League", portugueseTitle: "Ela é Demais Pra Mim", genre: .comedy, year: 2010),
    Movie(title: "Something Borrowed", portugueseTitle: "Muito Bem Acompanhada", genre: .comedy, duration: 5400, year: 2005),
    Movie(title: "Tangled", portugueseTitle: "Enrolados", genre: .animation, duration: 6000, year: 2010),
    Movie(title: "The Back-up Plan", portugueseTitle: "Plano B", genre: .comedy, duration: 6240, year: 2010),
    Movie(title: "The Curious Case of Benjamin Button", portugueseTitle: "O Curioso Caso de Benjamin Button", genre: .drama, duration: 9960, year: 2008, isFavorite: true),
    Movie(title: "The Duchess", portugueseTitle: "A Duquesa", genre: .biography, duration: 6600, year: 2008),
    Movie(title: "The Heartbreak Kid", portugueseTitle: "Antes Só do que Mal Casado", genre: .comedy, duration: 6960, year: 2007),
    Movie(title: "The Invention of Lying", portugueseTitle: "O Primeiro Mentiroso", genre: .comedy, duration: 6000, year: 2009),
    Movie(title: "The Proposal", portugueseTitle: "A Proposta", genre: .comedy, duration: 6480, year: 2009),
    Movie(title: "The Time Traveler's Wife", portugueseTitle: "Te Amarei Para Sempre", genre: .drama, duration: 6420, year: 2009),
    Movie(title: "The Twilight Saga: New Moon", portugueseTitle: "A Saga Crepúsculo: Lua Nova", genre: .adventure, duration: 7800, year: 2009),
    Movie(title: "The Ugly Truth", portugueseTitle: "A Verdade Nua e Crua", genre: .comedy, duration: 5760, year: 2009),
    Movie(title: "Twilight", portugueseTitle: "Crepúsculo", genre: .drama, duration: 7320, year: 2008),
    Movie(title: "The Twilight Saga: Breaking Dawn - Part 1", portugueseTitle: "A Saga Crepúsculo: Amanhecer - Parte 1", genre: .drama, duration: 7020, year: 2011),
    Movie(title: "Tyler Perry's Why Did I Get Married?", portugueseTitle: "Por Que Eu Me Casei?", genre: .comedy, year: 2007),
    Movie(title: "Valentine's Day", portugueseTitle: "Idas e Vindas do Amor", genre: .comedy, duration: 7500, year: 2010),
    Movie(title: "Wall-E", portugueseTitle: "WALL·E", genre: .animation, duration: 5880, year: 2008, isFavorite: true),
    Movie(title: "Waiting for Forever", portugueseTitle: "Esperar para Sempre", genre: .comedy, year: 2010),
    Movie(title: "Waitress", portugueseTitle: "Garçonete", genre: .comedy, duration: 6480, year: 2007),
    Movie(title: "Water for Elephants", portugueseTitle: "Água para Elefantes", genre: .drama, year: 2011),
    Movie(title: "What Happens in Vegas", portugueseTitle: "Jogo de Amor em Las Vegas", genre: .comedy, duration: 5940, year: 2008),
    Movie(title: "When in Rome - Fünf Männer sind vier zuviel", portugueseTitle: "Quando em Roma", genre: .comedy, duration: 5460, year: 2010),
    Movie(title: "You Will Meet a Tall Dark Stranger", portugueseTitle: "Você Vai Conhecer o Homem dos Seus Sonhos", genre: .comedy, year: 2010),
    Movie(title: "Youth in Revolt", portugueseTitle: "Rebelde com Causa", genre: .comedy, duration: 5400, year: 2009),
    Movie(title: "Zack and Miri Make a Porno", portugueseTitle: "Pagando Bem, que Mal Tem?", genre: .comedy, duration: 6060, year: 2008),
]


public let musicLibrary = [
    Music(title: "Nothin' On You [feat. Bruno Mars] (Album Version)", artist: "B.o.B", duration: 269.63546, year: 2010),
    Music(title: "Immigrant Song (Album Version)", artist: "Led Zeppelin", duration: 145.05751, year: 1970),
    Music(title: "This Christmas (LP Version)", artist: "Donny Hathaway", duration: 231.18322, year: nil),
//    Music(title: "If Today Was Your Last Day (Album Version)", artist: "Nickelback", duration: nil, year: 2008),
    Music(title: "Harder To Breathe", artist: "Maroon 5", duration: 173.66159, year: 2002),
    Music(title: "Blue Orchid", artist: "The White Stripes", duration: 160.31302, year: 2005),
    Music(title: "Just Say Yes", artist: "Snow Patrol", duration: 284.1073, year: 2009),
    Music(title: "They Reminisce Over You (Single Version)", artist: "Pete Rock & C.L. Smooth", duration: 286.69342, year: 1992),
    Music(title: "Exogenesis: Symphony Part 1 [Overture]", artist: "Muse", duration: 258.42893, year: nil),
    Music(title: "Inertiatic Esp", artist: "The Mars Volta", duration: 266.47465, year: 2003),
    Music(title: "The Loco-Motion", artist: "Little Eva", duration: 145.162, year: 1962),
    Music(title: "Innocence", artist: "Avril Lavigne", duration: 232.202, year: 2007),
    Music(title: "Umbrella", artist: "All Time Low", duration: 227.70893, year: 2008),
    Music(title: "You And Your Heart", artist: "Jack Johnson", duration: 196.20526, year: 2010),
    Music(title: "Face Drop", artist: "Sean Kingston", duration: 184.58077, year: 2009),
    Music(title: "Venice Queen (Album Version)", artist: "Red Hot Chili Peppers", duration: 367.01995, year: 2002),
    Music(title: "Genius", artist: "Kings Of Leon", duration: 168.82893, year: 2003),
    Music(title: "Wait Til You See My Smile", artist: "Alicia Keys", duration: 240.22159, year: 2009),
    Music(title: "Eriatarka", artist: "The Mars Volta", duration: 380.42077, year: 2003),
    Music(title: "All That's Left", artist: "Thrice", duration: 201.58649, year: 2003),
    Music(title: "Maybe", artist: "Janis Joplin", duration: 246.72608, year: 1969),
    Music(title: "Unforgettable Season", artist: "Cut Copy", duration: 195.21261, year: 2008),
    Music(title: "Streets On Fire (Explicit Album Version)", artist: "Lupe Fiasco", duration: 279.97995, year: nil),
    Music(title: "Little Brother", artist: "Grizzly Bear", duration: 384.67873, year: 2006),
//    Music(title: "The Cool (Amended Album Version)", artist: "Lupe Fiasco", duration: nil, year: nil),
    Music(title: "Swing Life Away", artist: "Rise Against", duration: 200.12363, year: 2003),
    Music(title: "English Summer Rain", artist: "Placebo", duration: 241.52771, year: 2003),
    Music(title: "This Is Not A Love Song", artist: "Public Image Ltd", duration: 251.50649, year: 1983),
    Music(title: "Crawling (Album Version)", artist: "Linkin Park", duration: 208.95302, year: 2000),
    Music(title: "IRM", artist: "Charlotte Gainsbourg", duration: 154.95791, year: 2009),
    Music(title: "Too Shy To Scream", artist: "AFI", duration: 176.61342, year: 2009),
    Music(title: "Lullaby", artist: "Dixie Chicks", duration: 351.84281, year: 2006),
    Music(title: "Never Gonna Give You Up", artist: "Rick Astley", duration: 211.69587, year: 1987),
    Music(title: "Send Me An Angel", artist: "Zeromancer", duration: 236.53832, year: 2001),
    Music(title: "Strip The Soul (album version)", artist: "Porcupine Tree", duration: 441.88689, year: 2002),
    Music(title: "Da Funk", artist: "Daft Punk", duration: 329.53424, year: 1995),
    Music(title: "Sickman", artist: "Alice In Chains", duration: 329.37751, year: 1992),
    Music(title: "Le Chat du CafA(c) des Artistes", artist: "Charlotte Gainsbourg", duration: 241.65832, year: 2009),
    Music(title: "Future", artist: "Cut Copy", duration: 312.08444, year: 2004),
    Music(title: "Summer Shudder", artist: "AFI", duration: 187.03628, year: 2006),
//    Music(title: "Alchemy Index Vol 1 Water 1 of 6", artist: "Thrice", duration: nil, year: nil),
    Music(title: "The Way I Loved You", artist: "Taylor Swift", duration: 245.36771, year: 2008),
    Music(title: "Fool For Your Loving", artist: "Whitesnake", duration: 250.3571, year: 1980),
    Music(title: "You Appearing", artist: "M83", duration: 219.24526, year: 2008),
    Music(title: "Slave To The Wage", artist: "Placebo", duration: 246.96118, year: 2000),
    Music(title: "War?", artist: "System of a Down", duration: 160.49587, year: 1996),
    Music(title: "You Left Me", artist: "The Maine", duration: 209.00526, year: 2008),
    Music(title: "Do You Want To", artist: "Franz Ferdinand", duration: 214.9873, year: 2005),
    Music(title: "Spin (Album Version)", artist: "Taking Back Sunday", duration: 219.79383, year: 2006),
    Music(title: "Hunger Strike", artist: "Temple Of The Dog", duration: 243.9571, year: 1991),
    Music(title: "Ocean Drive", artist: "Lighthouse Family", duration: 241.8673, year: 1995),
    Music(title: "Emergency (Album Version)", artist: "Paramore", duration: 243.51302, year: nil),
//    Music(title: "Don't Matter", artist: "Akon", duration: nil, year: 2006),
    Music(title: "A Martyr For My Love For You", artist: "The White Stripes", duration: 259.5522, year: 2007),
    Music(title: "Can't Make You Love Me", artist: "Britney Spears", duration: 196.80608, year: 2000),
    Music(title: "Remember Me Lover (Album Version)", artist: "Porcupine Tree", duration: 454.16444, year: 2009),
    Music(title: "Fire", artist: "Jimi Hendrix", duration: 192.23465, year: 1969),
    Music(title: "The Earth Will Shake", artist: "Thrice", duration: 329.7171, year: 2005),
    Music(title: "Affliction", artist: "AFI", duration: 328.72444, year: 2006),
    Music(title: "Savin' Me", artist: "Nickelback", duration: 217.62567, year: 2005),
    Music(title: "Angie (1993 Digital Remaster)", artist: "The Rolling Stones", duration: 271.49016, year: nil),
    Music(title: "Interlude (Album Version)", artist: "My Chemical Romance", duration: 57.18159, year: 2004),
    Music(title: "Drive", artist: "The Cars", duration: 234.50077, year: 1984),
//    Music(title: "Firestarter", artist: "The Prodigy", duration: nil, year: 1996),
    Music(title: "Between Love & Hate", artist: "The Strokes", duration: 191.29424, year: 2003),
    Music(title: "Nevada's Grace (Album Version)", artist: "Atreyu", duration: 227.99628, year: 2004),
    Music(title: "Can't Take My Eyes Off You", artist: "Muse", duration: 211.12118, year: nil),
    Music(title: "The Space Between", artist: "DAVE MATTHEWS BAND", duration: 293.66812, year: 2001),
    Music(title: "Waiting", artist: "Porcupine Tree", duration: 416.80934, year: 1997),
    Music(title: "Take The Veil Cerpin Taxt", artist: "The Mars Volta", duration: 521.63873, year: 2003),
    Music(title: "Panama (Remastered Album Version)", artist: "Van Halen", duration: 209.29261, year: nil),
    Music(title: "Lesson Learned", artist: "Alice In Chains", duration: 256.522, year: 2009),
    Music(title: "Fortunate Fool", artist: "Jack Johnson", duration: 228.70159, year: 2000),
    Music(title: "Defend You (Album Version)", artist: "Silverstein", duration: 208.16934, year: 2005),
//    Music(title: "One More Night", artist: "Phil Collins", duration: nil, year: 1985),
    Music(title: "State of Emergency", artist: "Nick Jonas & The Administration", duration: 214.72608, year: 2010),
//    Music(title: "Tel Que Tu Es", artist: "Charlotte Gainsbourg", duration: nil, year: 2006),
    Music(title: "Like It Like That", artist: "A Tribe Called Quest", duration: 166.86975, year: 1998),
    Music(title: "God Smack", artist: "Alice In Chains", duration: 230.60853, year: 1992),
    Music(title: "Dope Nose", artist: "Weezer", duration: 137.37751, year: 2002),
    Music(title: "Year Zero", artist: "30 Seconds To Mars", duration: 472.39791, year: 2002),
    Music(title: "I Could Be Dreaming", artist: "Belle and Sebastian", duration: 226.92526, year: 1996),
    Music(title: "Street Lights", artist: "Kanye West", duration: 189.962, year: 2008),
    Music(title: "November Has Come", artist: "Gorillaz", duration: 160.96608, year: 2005),
    Music(title: "Darling_ I Want To Destroy You", artist: "AFI", duration: 223.29424, year: 2009),
    Music(title: "Rock The House (Explicit)", artist: "Gorillaz", duration: 249.93914, year: 2001),
    Music(title: "White Light", artist: "Gorillaz", duration: 128.41751, year: 2005),
    Music(title: "The Way I Am", artist: "Eminem", duration: 289.30567, year: 2000),
    Music(title: "Moon Loop (Improvisation)", artist: "Porcupine Tree", duration: 978.442, year: nil),
    Music(title: "I'm Back", artist: "Eminem", duration: 312.2673, year: 2000),
    Music(title: "House Of Pain", artist: "Van Halen", duration: 199.10485, year: 1983),
    Music(title: "Marrakech", artist: "ATB", duration: 262.21669, year: 2004),
    Music(title: "One I Love", artist: "Coldplay", duration: 274.41587, year: 2002),
//    Music(title: "School", artist: "Nirvana", duration: nil, year: nil),
//    Music(title: "I Am The Walrus", artist: "Spooky Tooth / Mike Harrison", duration: nil, year: 1970),
    Music(title: "I Know A Place", artist: "Joe Bonamassa", duration: 258.7424, year: 2010),
    Music(title: "Push It", artist: "Salt-N-Pepa", duration: 207.62077, year: 1988),
    Music(title: "The Earth Isn't Humming", artist: "Thrice", duration: 349.80526, year: 2008),
//    Music(title: "Play", artist: "Jennifer Lopez", duration: nil, year: 2001),
    Music(title: "Next Year", artist: "Foo Fighters", duration: 274.65098, year: 1999),
]


public let mediaLibrary: [Any] = [
    Movie(title: "Water for Elephants", portugueseTitle: "Água para Elefantes", genre: .drama, year: 2011),
    Movie(title: "Nick and Norah's Infinite Playlist", portugueseTitle: "Nick & Norah: Uma Noite de Amor e Música", genre: .comedy, duration: 5400, year: 2008),
    Music(title: "Like It Like That", artist: "A Tribe Called Quest", duration: 166.86975, year: 1998),
    Music(title: "Savin' Me", artist: "Nickelback", duration: 217.62567, year: 2005),
    Music(title: "Fire", artist: "Jimi Hendrix", duration: 192.23465, year: 1969),
    Music(title: "Nothin' On You [feat. Bruno Mars] (Album Version)", artist: "B.o.B", duration: 269.63546, year: 2010),
    Music(title: "Drive", artist: "The Cars", duration: 234.50077, year: 1984),
    Music(title: "All That's Left", artist: "Thrice", duration: 201.58649, year: 2003),
    Movie(title: "Fireproof", portugueseTitle: "À Prova de Fogo", genre: .drama, year: 2008),
    Movie(title: "Sex and the City 2", genre: .comedy, duration: 8760, year: 2010),
    Music(title: "Can't Make You Love Me", artist: "Britney Spears", duration: 196.80608, year: 2000),
    Movie(title: "A Serious Man", portugueseTitle: "Um Homem Sério", genre: .comedy, duration: 6360, year: 2009),
    Music(title: "I Could Be Dreaming", artist: "Belle and Sebastian", duration: 226.92526, year: 1996),
    Music(title: "Play", artist: "Jennifer Lopez", duration: nil, year: 2001),
    Music(title: "Genius", artist: "Kings Of Leon", duration: 168.82893, year: 2003),
    Music(title: "Waiting", artist: "Porcupine Tree", duration: 416.80934, year: 1997),
    Movie(title: "No Reservations", portugueseTitle: "Sem Reservas", genre: .comedy, duration: 6240, year: 2007),
    Music(title: "Firestarter", artist: "The Prodigy", duration: nil, year: 1996),
    Music(title: "Just Say Yes", artist: "Snow Patrol", duration: 284.1073, year: 2009),
    Music(title: "Eriatarka", artist: "The Mars Volta", duration: 380.42077, year: 2003),
    Movie(title: "License to Wed", portugueseTitle: "Licença para Casar", genre: .comedy, duration: 5460, year: 2007),
    Music(title: "English Summer Rain", artist: "Placebo", duration: 241.52771, year: 2003),
    Music(title: "Swing Life Away", artist: "Rise Against", duration: 200.12363, year: 2003),
    Movie(title: "Enchanted", portugueseTitle: "Encantada", genre: .animation, duration: 6420, year: 2007),
    Music(title: "God Smack", artist: "Alice In Chains", duration: 230.60853, year: 1992),
    Music(title: "Angie (1993 Digital Remaster)", artist: "The Rolling Stones", duration: 271.49016, year: nil),
    Music(title: "Umbrella", artist: "All Time Low", duration: 227.70893, year: 2008),
    Music(title: "Future", artist: "Cut Copy", duration: 312.08444, year: 2004),
    Music(title: "Little Brother", artist: "Grizzly Bear", duration: 384.67873, year: 2006),
    Music(title: "Innocence", artist: "Avril Lavigne", duration: 232.202, year: 2007),
    Music(title: "The Cool (Amended Album Version)", artist: "Lupe Fiasco", duration: nil, year: nil),
    Movie(title: "Gnomeo and Juliet", genre: .animation, year: 2011),
    Music(title: "Defend You (Album Version)", artist: "Silverstein", duration: 208.16934, year: 2005),
    Music(title: "Hunger Strike", artist: "Temple Of The Dog", duration: 243.9571, year: 1991),
    Music(title: "The Earth Will Shake", artist: "Thrice", duration: 329.7171, year: 2005),
    Music(title: "The Loco-Motion", artist: "Little Eva", duration: 145.162, year: 1962),
    Movie(title: "The Proposal", portugueseTitle: "A Proposta", genre: .comedy, duration: 6480, year: 2009),
    Movie(title: "Valentine's Day", portugueseTitle: "Idas e Vindas do Amor", genre: .comedy, duration: 7500, year: 2010),
    Movie(title: "27 Dresses", portugueseTitle: "Vestida para Casar", genre: .comedy, duration: 6660, year: 2008),
    Movie(title: "Four Christmases", portugueseTitle: "Surpresas do Amor", genre: .comedy, duration: 5280, year: 2008),
    Movie(title: "Going the Distance", portugueseTitle: "Amor à Distância", genre: .comedy, year: 2010),
    Movie(title: "Jane Eyre", genre: .drama, duration: 7200, year: 2011),
    Music(title: "Le Chat du CafA(c) des Artistes", artist: "Charlotte Gainsbourg", duration: 241.65832, year: 2009),
    Movie(title: "Knocked Up", portugueseTitle: "Ligeiramente Grávidos", genre: .comedy, duration: 7740, year: 2007),
    Music(title: "Sickman", artist: "Alice In Chains", duration: 329.37751, year: 1992),
    Music(title: "Year Zero", artist: "30 Seconds To Mars", duration: 472.39791, year: 2002),
    Movie(title: "Tyler Perry's Why Did I Get Married?", portugueseTitle: "Por Que Eu Me Casei?", genre: .comedy, year: 2007),
    Movie(title: "Over Her Dead Body", portugueseTitle: "Nem por Cima do Meu Cadáver", genre: .comedy, duration: 5700, year: 2008),
    Movie(title: "High School Musical 3: Senior Year", portugueseTitle: "High School Musical 3: Ano da Formatura", genre: .comedy, duration: 6720, year: 2008),
    Music(title: "Exogenesis: Symphony Part 1 [Overture]", artist: "Muse", duration: 258.42893, year: nil),
    Music(title: "Harder To Breathe", artist: "Maroon 5", duration: 173.66159, year: 2002),
    Music(title: "Between Love & Hate", artist: "The Strokes", duration: 191.29424, year: 2003),
    Movie(title: "He's Just Not That Into You", portugueseTitle: "Ele Não Está Tão a Fim de Você", genre: .comedy, duration: 7740, year: 2009),
    Movie(title: "The Back-up Plan", portugueseTitle: "Plano B", genre: .comedy, duration: 6240, year: 2010),
    Movie(title: "Leap Year", portugueseTitle: "Casa Comigo?", genre: .comedy, year: 2010),
    Movie(title: "One Day (Siempre el mismo día)", portugueseTitle: "Um Dia", genre: .drama, duration: 6420, year: 2011),
    Music(title: "Spin (Album Version)", artist: "Taking Back Sunday", duration: 219.79383, year: 2006),
    Movie(title: "My Week with Marilyn", portugueseTitle: "Sete Dias com Marilyn", genre: .biography, duration: 5940, year: 2011),
    Movie(title: "The Heartbreak Kid", portugueseTitle: "Antes Só do que Mal Casado", genre: .comedy, duration: 6960, year: 2007),
    Movie(title: "Zack and Miri Make a Porno", portugueseTitle: "Pagando Bem, que Mal Tem?", genre: .comedy, duration: 6060, year: 2008),
    Music(title: "Too Shy To Scream", artist: "AFI", duration: 176.61342, year: 2009),
    Movie(title: "Midnight in Paris", portugueseTitle: "Meia-Noite em Paris", genre: .comedy, year: 2011),
    Music(title: "Remember Me Lover (Album Version)", artist: "Porcupine Tree", duration: 454.16444, year: 2009),
    Music(title: "Streets On Fire (Explicit Album Version)", artist: "Lupe Fiasco", duration: 279.97995, year: nil),
    Music(title: "Strip The Soul (album version)", artist: "Porcupine Tree", duration: 441.88689, year: 2002),
    Movie(title: "Marley and Me", portugueseTitle: "Marley & Eu", genre: .comedy, year: 2008),
    Movie(title: "It's Complicated", portugueseTitle: "Simplesmente Complicado", genre: .comedy, year: 2009),
    Movie(title: "The Time Traveler's Wife", portugueseTitle: "Te Amarei Para Sempre", genre: .drama, duration: 6420, year: 2009),
    Movie(title: "Our Family Wedding", portugueseTitle: "Nossa União, Muita Confusão", genre: .comedy, year: 2010),
    Music(title: "Slave To The Wage", artist: "Placebo", duration: 246.96118, year: 2000),
    Music(title: "Venice Queen (Album Version)", artist: "Red Hot Chili Peppers", duration: 367.01995, year: 2002),
    Movie(title: "(500) Days of Summer", portugueseTitle: "(500) Dias com Ela", genre: .comedy, duration: 5700, year: 2009),
    Movie(title: "Mamma Mia!", portugueseTitle: "Mamma Mia! O Filme", genre: .comedy, duration: 6480, year: 2008),
    Music(title: "Crawling (Album Version)", artist: "Linkin Park", duration: 208.95302, year: 2000),
    Movie(title: "Letters to Juliet", portugueseTitle: "Cartas para Julieta", genre: .adventure, year: 2010),
    Music(title: "Emergency (Album Version)", artist: "Paramore", duration: 243.51302, year: nil),
    Music(title: "If Today Was Your Last Day (Album Version)", artist: "Nickelback", duration: nil, year: 2008),
    Movie(title: "Wall-E", portugueseTitle: "WALL·E", genre: .animation, duration: 5880, year: 2008),
    Music(title: "This Christmas (LP Version)", artist: "Donny Hathaway", duration: 231.18322, year: nil),
    Movie(title: "Youth in Revolt", portugueseTitle: "Rebelde com Causa", genre: .comedy, duration: 5400, year: 2009),
    Movie(title: "Monte Carlo", genre: .adventure, year: 2011),
    Music(title: "You Appearing", artist: "M83", duration: 219.24526, year: 2008),
    Movie(title: "I Love You Phillip Morris", portugueseTitle: "O Golpista do Ano", genre: .biography, duration: 6120, year: 2009),
    Music(title: "Wait Til You See My Smile", artist: "Alicia Keys", duration: 240.22159, year: 2009),
    Movie(title: "Penelope", genre: .comedy, duration: 6240, year: 2006),
    Music(title: "State of Emergency", artist: "Nick Jonas & The Administration", duration: 214.72608, year: 2010),
    Movie(title: "The Curious Case of Benjamin Button", portugueseTitle: "O Curioso Caso de Benjamin Button", genre: .drama, duration: 9960, year: 2008),
    Music(title: "I'm Back", artist: "Eminem", duration: 312.2673, year: 2000),
    Music(title: "Unforgettable Season", artist: "Cut Copy", duration: 195.21261, year: 2008),
    Music(title: "This Is Not A Love Song", artist: "Public Image Ltd", duration: 251.50649, year: 1983),
    Movie(title: "Remember Me", portugueseTitle: "Viva - A Vida é uma Festa", genre: .animation, year: 2017),
    Music(title: "Fool For Your Loving", artist: "Whitesnake", duration: 250.3571, year: 1980),
    Movie(title: "Something Borrowed", portugueseTitle: "Muito Bem Acompanhada", genre: .comedy, duration: 5400, year: 2005),
    Movie(title: "Made of Honor", portugueseTitle: "O Melhor Amigo da Noiva", genre: .comedy, duration: 6060, year: 2008),
    Music(title: "Street Lights", artist: "Kanye West", duration: 189.962, year: 2008),
    Movie(title: "Rachel Getting Married", portugueseTitle: "O Casamento de Rachel", genre: .drama, duration: 6780, year: 2008),
    Movie(title: "Tangled", portugueseTitle: "Enrolados", genre: .animation, duration: 6000, year: 2010),
    Music(title: "The Space Between", artist: "DAVE MATTHEWS BAND", duration: 293.66812, year: 2001),
    Movie(title: "The Ugly Truth", portugueseTitle: "A Verdade Nua e Crua", genre: .comedy, duration: 5760, year: 2009),
    Music(title: "November Has Come", artist: "Gorillaz", duration: 160.96608, year: 2005),
    Movie(title: "Not Easily Broken", portugueseTitle: "Ponto de Decisão", genre: .drama, duration: 5940, year: 2009),
    Music(title: "Marrakech", artist: "ATB", duration: 262.21669, year: 2004),
    Movie(title: "Ghosts of Girlfriends Past", portugueseTitle: "Minhas Adoráveis Ex-Namoradas", genre: .comedy, year: 2009),
    Music(title: "Interlude (Album Version)", artist: "My Chemical Romance", duration: 57.18159, year: 2004),
    Music(title: "I Am The Walrus", artist: "Spooky Tooth / Mike Harrison", duration: nil, year: 1970),
    Music(title: "Send Me An Angel", artist: "Zeromancer", duration: 236.53832, year: 2001),
    Movie(title: "What Happens in Vegas", portugueseTitle: "Jogo de Amor em Las Vegas", genre: .comedy, duration: 5940, year: 2008),
    Music(title: "Take The Veil Cerpin Taxt", artist: "The Mars Volta", duration: 521.63873, year: 2003),
    Music(title: "Maybe", artist: "Janis Joplin", duration: 246.72608, year: 1969),
    Music(title: "One I Love", artist: "Coldplay", duration: 274.41587, year: 2002),
    Music(title: "One More Night", artist: "Phil Collins", duration: nil, year: 1985),
    Music(title: "White Light", artist: "Gorillaz", duration: 128.41751, year: 2005),
    Movie(title: "Life as We Know It", portugueseTitle: "Juntos Pelo Acaso", genre: .comedy, year: 2010),
    Music(title: "I Know A Place", artist: "Joe Bonamassa", duration: 258.7424, year: 2010),
    Music(title: "House Of Pain", artist: "Van Halen", duration: 199.10485, year: 1983),
    Music(title: "Rock The House (Explicit)", artist: "Gorillaz", duration: 249.93914, year: 2001),
    Music(title: "Fortunate Fool", artist: "Jack Johnson", duration: 228.70159, year: 2000),
    Music(title: "They Reminisce Over You (Single Version)", artist: "Pete Rock & C.L. Smooth", duration: 286.69342, year: 1992),
    Music(title: "Can't Take My Eyes Off You", artist: "Muse", duration: 211.12118, year: nil),
    Movie(title: "Killers", portugueseTitle: "Par Perfeito", genre: .action, duration: 6000, year: 2010),
    Movie(title: "Music and Lyrics", portugueseTitle: "Letra e Música", genre: .comedy, duration: 5700, year: 2007),
    Movie(title: "You Will Meet a Tall Dark Stranger", portugueseTitle: "Você Vai Conhecer o Homem dos Seus Sonhos", genre: .comedy, year: 2010),
    Movie(title: "Dear John", portugueseTitle: "Querido John", genre: .drama, duration: 6480, year: 2010),
    Movie(title: "Just Wright - In diesem Spiel zählt jeder Treffer", portugueseTitle: "Jogada Certa", genre: .comedy, year: 2010),
    Music(title: "Lesson Learned", artist: "Alice In Chains", duration: 256.522, year: 2009),
    Music(title: "Blue Orchid", artist: "The White Stripes", duration: 160.31302, year: 2005),
    Music(title: "Moon Loop (Improvisation)", artist: "Porcupine Tree", duration: 978.442, year: nil),
    Music(title: "Don't Matter", artist: "Akon", duration: nil, year: 2006),
    Music(title: "Panama (Remastered Album Version)", artist: "Van Halen", duration: 209.29261, year: nil),
    Music(title: "Tel Que Tu Es", artist: "Charlotte Gainsbourg", duration: nil, year: 2006),
    Movie(title: "Waitress", portugueseTitle: "Garçonete", genre: .comedy, duration: 6480, year: 2007),
    Music(title: "Immigrant Song (Album Version)", artist: "Led Zeppelin", duration: 145.05751, year: 1970),
    Music(title: "Alchemy Index Vol 1 Water 1 of 6", artist: "Thrice", duration: nil, year: nil),
    Music(title: "School", artist: "Nirvana", duration: nil, year: nil),
    Music(title: "The Way I Am", artist: "Eminem", duration: 289.30567, year: 2000),
    Movie(title: "A Dangerous Method", portugueseTitle: "Um Método Perigoso", genre: .biography, duration: 5940, year: 2011),
    Music(title: "Never Gonna Give You Up", artist: "Rick Astley", duration: 211.69587, year: 1987),
    Movie(title: "P.S. I Love You", portugueseTitle: "P.S. Eu te Amo", genre: .drama, duration: 7560, year: 2007),
    Movie(title: "The Invention of Lying", portugueseTitle: "O Primeiro Mentiroso", genre: .comedy, duration: 6000, year: 2009),
    Music(title: "IRM", artist: "Charlotte Gainsbourg", duration: 154.95791, year: 2009),
    Movie(title: "The Twilight Saga: New Moon", portugueseTitle: "A Saga Crepúsculo: Lua Nova", genre: .adventure, duration: 7800, year: 2009),
    Music(title: "A Martyr For My Love For You", artist: "The White Stripes", duration: 259.5522, year: 2007),
    Movie(title: "Twilight", portugueseTitle: "Crepúsculo", genre: .drama, duration: 7320, year: 2008),
    Movie(title: "Love Happens", portugueseTitle: "O Amor Acontece", genre: .drama, year: 2009),
    Movie(title: "The Duchess", portugueseTitle: "A Duquesa", genre: .biography, duration: 6600, year: 2008),
    Movie(title: "Beginners, así se siente el amor", portugueseTitle: "Toda Forma de Amor", genre: .comedy, duration: 6300, year: 2010),
    Music(title: "Ocean Drive", artist: "Lighthouse Family", duration: 241.8673, year: 1995),
    Movie(title: "Sex and the City", genre: .comedy, duration: 1800, year: 1998),
    Music(title: "War?", artist: "System of a Down", duration: 160.49587, year: 1996),
    Movie(title: "When in Rome - Fünf Männer sind vier zuviel", portugueseTitle: "Quando em Roma", genre: .comedy, duration: 5460, year: 2010),
    Music(title: "Darling_ I Want To Destroy You", artist: "AFI", duration: 223.29424, year: 2009),
    Music(title: "The Way I Loved You", artist: "Taylor Swift", duration: 245.36771, year: 2008),
    Music(title: "Da Funk", artist: "Daft Punk", duration: 329.53424, year: 1995),
    Music(title: "Next Year", artist: "Foo Fighters", duration: 274.65098, year: 1999),
    Music(title: "Affliction", artist: "AFI", duration: 328.72444, year: 2006),
    Movie(title: "New Year's Eve", portugueseTitle: "Noite de Ano Novo", genre: .comedy, duration: 6780, year: 2011),
    Music(title: "You And Your Heart", artist: "Jack Johnson", duration: 196.20526, year: 2010),
    Movie(title: "Waiting for Forever", portugueseTitle: "Esperar para Sempre", genre: .comedy, year: 2010),
    Music(title: "Face Drop", artist: "Sean Kingston", duration: 184.58077, year: 2009),
    Movie(title: "She's Out of My League", portugueseTitle: "Ela é Demais Pra Mim", genre: .comedy, year: 2010),
    Movie(title: "Good Luck Chuck", portugueseTitle: "Maldita Sorte", genre: .comedy, duration: 6060, year: 2007),
    Music(title: "You Left Me", artist: "The Maine", duration: 209.00526, year: 2008),
    Music(title: "Push It", artist: "Salt-N-Pepa", duration: 207.62077, year: 1988),
    Movie(title: "Miss Pettigrew Lives for a Day", portugueseTitle: "A Vida num Só Dia", genre: .comedy, duration: 5520, year: 2008),
    Music(title: "Nevada's Grace (Album Version)", artist: "Atreyu", duration: 227.99628, year: 2004),
    Music(title: "Inertiatic Esp", artist: "The Mars Volta", duration: 266.47465, year: 2003),
    Music(title: "Lullaby", artist: "Dixie Chicks", duration: 351.84281, year: 2006),
    Movie(title: "Across the Universe", genre: .drama, duration: 7980, year: 2007),
    Music(title: "Summer Shudder", artist: "AFI", duration: 187.03628, year: 2006),
    Music(title: "The Earth Isn't Humming", artist: "Thrice", duration: 349.80526, year: 2008),
    Movie(title: "Love & Other Drugs", portugueseTitle: "Amor e Outras Drogas", genre: .comedy, duration: 6720, year: 2010),
    Music(title: "Do You Want To", artist: "Franz Ferdinand", duration: 214.9873, year: 2005),
    Movie(title: "The Twilight Saga: Breaking Dawn - Part 1", portugueseTitle: "A Saga Crepúsculo: Amanhecer - Parte 1", genre: .drama, duration: 7020, year: 2011),
    Music(title: "Dope Nose", artist: "Weezer", duration: 137.37751, year: 2002),
]
